version: "3.3"

services:
  database:
    container_name: mercadoalegria_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=mercadoalegria
      - POSTGRES_USER=mercadoalegria
      - POSTGRES_DB=mercadoalegria
    ports:
      - 5434:5432
