# Generated by Django 5.0.2 on 2024-02-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_subcategoria_produto_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
