# Generated by Django 5.0.2 on 2024-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_carrinho_carrinhoitem_carrinho_produtos'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrinhoitem',
            constraint=models.UniqueConstraint(fields=('carrinho', 'produto'), name='unique_carrinho__produto'),
        ),
    ]
