# Generated by Django 5.0.2 on 2024-05-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_carrinho_carrinhoitem_carrinho_produtos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrinhoitem',
            unique_together={('carrinho', 'produto')},
        ),
    ]
